# Generated by Django 2.2.7 on 2019-11-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_post',
        ),
    ]
