# Generated by Django 2.2.7 on 2019-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_published_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_post',
            field=models.BooleanField(default=False),
        ),
    ]
