# Generated by Django 2.2.7 on 2019-11-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
